upload to s3:
    image:
        name: banst/awscli
        entrypoint: [""]
    script:
        - aws configure set region us-east-1
        - touch test.txt
        - aws s3 cp test.txt s3://$s3_bucket/test.txt