retro-guitars:
 script:
  — apt-get update -qy
  — apt-get install -y python-dev python-pip
  — pip install -r requirements.txt
  — export MONGOHQ_URL=$MONGO_URL
 
production:
 type: deploy
 script:
  — apt-get update -qy
  — apt-get install -y ruby-dev
  — gem install dpl
  - dpl --provider=heroku --app=retro-guitars --api-key=a55f9895-3e86-4095-8c1e-63a963b2289d

only:
 — master
